// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEk4JaxybsyfGZUCXxoCBYoWohwA1UiM',
    appId: '1:317858009144:web:611cabd4e14e69969056cd',
    messagingSenderId: '317858009144',
    projectId: 'scary-baboon-night-escape',
    authDomain: 'scary-baboon-night-escape.firebaseapp.com',
    storageBucket: 'scary-baboon-night-escape.firebasestorage.app',
    measurementId: 'G-MYM334TVS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Ek0959y42njs0gp3TdmVDE9x2GQDzD8',
    appId: '1:317858009144:android:c601d072ab385d049056cd',
    messagingSenderId: '317858009144',
    projectId: 'scary-baboon-night-escape',
    storageBucket: 'scary-baboon-night-escape.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYmT_SuxjFU2pURClT_DnWiSAGSkiEYTw',
    appId: '1:317858009144:ios:33ccdf852f3290b19056cd',
    messagingSenderId: '317858009144',
    projectId: 'scary-baboon-night-escape',
    storageBucket: 'scary-baboon-night-escape.firebasestorage.app',
    iosBundleId: 'com.FutureDialLabs.facebook.video.downloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYmT_SuxjFU2pURClT_DnWiSAGSkiEYTw',
    appId: '1:317858009144:ios:33ccdf852f3290b19056cd',
    messagingSenderId: '317858009144',
    projectId: 'scary-baboon-night-escape',
    storageBucket: 'scary-baboon-night-escape.firebasestorage.app',
    iosBundleId: 'com.FutureDialLabs.facebook.video.downloader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGEk4JaxybsyfGZUCXxoCBYoWohwA1UiM',
    appId: '1:317858009144:web:0c8ea7d2451893429056cd',
    messagingSenderId: '317858009144',
    projectId: 'scary-baboon-night-escape',
    authDomain: 'scary-baboon-night-escape.firebaseapp.com',
    storageBucket: 'scary-baboon-night-escape.firebasestorage.app',
    measurementId: 'G-S777MGHJFD',
  );
}
